# Generated by Django 6.0.4 on 2026-04-11 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('nickname', models.CharField(max_length=100, verbose_name='Pseudonim')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Artysta',
                'verbose_name_plural': 'Artyści',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa gatunku')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gatunek',
                'verbose_name_plural': 'Gatunki',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł albumu')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('release_date', models.DateField(verbose_name='Data wydania')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Okładka')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='music.artist', verbose_name='Artysta')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albumy',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='music.genre', verbose_name='Gatunek'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa playlisty')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Playlista',
                'verbose_name_plural': 'Playlisty',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł piosenki')),
                ('duration_sec', models.PositiveIntegerField(help_text='Czas trwania w sekundach', verbose_name='Czas trwania (s)')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Piosenka',
                'verbose_name_plural': 'Piosenki',
            },
        ),
        migrations.CreateModel(
            name='PlaylistPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano dnia')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist', verbose_name='Playlista')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song', verbose_name='Piosenka')),
            ],
            options={
                'verbose_name': 'Pozycja na playliście',
                'verbose_name_plural': 'Pozycje na playliście',
                'ordering': ['order'],
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='music.PlaylistPosition', to='music.song', verbose_name='Piosenki'),
        ),
    ]
