# Generated by Django 6.0.4 on 2026-04-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='music.song'),
        ),
    ]
