# Generated by Django 6.0.4 on 2026-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='play_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Suma odtworzeń albumu'),
        ),
        migrations.AddField(
            model_name='song',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liczba polubień'),
        ),
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liczba odtworzeń'),
        ),
    ]
