# Generated by Django 6.0.4 on 2026-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_play_count_song_likes_count_song_play_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration_sec',
            field=models.PositiveIntegerField(default=0, help_text='Czas trwania w sekundach', verbose_name='Czas trwania (s)'),
        ),
    ]
