# Generated by Django 6.0.4 on 2026-04-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_song_duration_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration_sec',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Czas trwania (automatycznie z pliku)', verbose_name='Czas trwania (s)'),
        ),
    ]
