# Generated by Django 6.0.4 on 2026-04-17 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_song_duration_sec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='Data odtworzenia')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_plays', to='music.song')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odtwarzanie',
                'verbose_name_plural': 'Odtwarzania',
                'ordering': ['-played_at'],
            },
        ),
    ]
