# Generated by Django 6.0.4 on 2026-04-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_songplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='play_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liczba odtworzeń playlisty'),
        ),
    ]
