# Generated by Django 6.0.4 on 2026-04-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_playlist_play_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='play_count',
        ),
        migrations.AddField(
            model_name='songplay',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_plays', to='music.playlist'),
        ),
    ]
