# Generated by Django 6.0.4 on 2026-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_playlist_play_count_songplay_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Publiczna'),
        ),
    ]
