# Generated by Django 6.0.4 on 2026-04-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_playlist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liczba polubień'),
        ),
    ]
