# Generated by Django 6.0.4 on 2026-04-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_album_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_albums',
            field=models.ManyToManyField(blank=True, to='music.album'),
        ),
    ]
