# Generated by Django 6.0.4 on 2026-04-23 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_profile_instagram_url_profile_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Data polubienia')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_positions', to='music.profile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_positions', to='music.song')),
            ],
            options={
                'verbose_name': 'Polubiony utwór',
                'verbose_name_plural': 'Polubione utwory',
                'ordering': ['-added_at'],
                'unique_together': {('profile', 'song')},
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_songs',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', through='music.LikedSong', to='music.song'),
        ),
    ]
