# Generated by Django 6.0.4 on 2026-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_likedsong_alter_profile_liked_songs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedsong',
            options={'ordering': ['order', '-added_at'], 'verbose_name': 'Polubiony utwór', 'verbose_name_plural': 'Polubione utwory'},
        ),
        migrations.AddField(
            model_name='likedsong',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność'),
        ),
    ]
