# Generated by Django 6.0.4 on 2026-04-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_add_order_to_liked_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='music.profile'),
        ),
    ]
