# Generated by Django 6.0.4 on 2026-04-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_public',
        ),
        migrations.AddField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publiczny (widoczny dla wszystkich)'), ('followers', 'Tylko dla obserwujących'), ('private', 'Prywatny')], default='private', max_length=10, verbose_name='Widoczność profilu'),
        ),
    ]
