# Generated by Django 6.0.4 on 2026-04-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_remove_profile_is_public_profile_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia aktywność'),
        ),
    ]
