# Generated by Django 6.0.4 on 2026-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_playlists',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='music.playlist'),
        ),
    ]
