# Generated by Django 6.0.4 on 2026-04-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_profile_followed_playlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followed_playlists',
        ),
        migrations.CreateModel(
            name='FollowedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.profile')),
            ],
            options={
                'ordering': ['order', '-followed_at'],
                'unique_together': {('profile', 'playlist')},
            },
        ),
    ]
