# Generated by Django 6.0.4 on 2026-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_remove_profile_followed_playlists_followedplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_playlists',
            field=models.ManyToManyField(blank=True, related_name='followed_by', through='music.FollowedPlaylist', to='music.playlist'),
        ),
    ]
