# Generated by Django 6.0.4 on 2026-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_profile_followed_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_playback',
            field=models.JSONField(blank=True, null=True, verbose_name='Ostatnie odtwarzanie'),
        ),
    ]
