# Generated by Django 6.0.4 on 2026-04-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_profile_last_playback'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_songs', to='music.artist', verbose_name='Artyści gościnni'),
        ),
    ]
