# Generated by Django 6.0.4 on 2026-04-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_song_featured_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_stats_publicly',
            field=models.BooleanField(default=True, verbose_name='Pokazuj statystyki publicznie'),
        ),
    ]
