# Generated by Django 6.0.4 on 2026-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_profile_show_stats_publicly'),
    ]

    operations = [
        migrations.AddField(
            model_name='songplay',
            name='listened_duration_sec',
            field=models.PositiveIntegerField(default=0, verbose_name='Przesłuchany czas (s)'),
        ),
    ]
