# Generated by Django 6.0.4 on 2026-04-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_songplay_listened_duration_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_stats_publicly',
        ),
        migrations.AddField(
            model_name='profile',
            name='show_detailed_stats_publicly',
            field=models.BooleanField(default=True, verbose_name='Pokazuj szczegółowe statystyki publicznie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_profile_stats_publicly',
            field=models.BooleanField(default=True, verbose_name='Pokazuj statystyki nastroju publicznie'),
        ),
    ]
