# Generated by Django 6.0.4 on 2026-04-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_remove_profile_show_detailed_stats_publicly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_stats_publicly',
        ),
        migrations.AddField(
            model_name='profile',
            name='show_detailed_stats_publicly',
            field=models.BooleanField(default=True, verbose_name='Dostęp do szczegółowych statystyk publiczny'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_profile_stats_publicly',
            field=models.BooleanField(default=True, verbose_name='Pokazuj wykresy na profilu publicznie'),
        ),
    ]
