# Generated by Django 6.0.4 on 2026-04-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_remove_profile_show_stats_publicly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='produced_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Producent'),
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografia'),
        ),
    ]
