# Generated by Django 6.0.4 on 2026-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_album_produced_by_artist_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_artists', to='music.profile', verbose_name='Obserwujący'),
        ),
    ]
