# Generated by Django 6.0.4 on 2026-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_discoverylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('O', 'Nie chcę podawać / Inna')], default='O', max_length=1, verbose_name='Płeć'),
        ),
        migrations.DeleteModel(
            name='DiscoveryLog',
        ),
    ]
