# Generated by Django 6.0.4 on 2026-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_profile_gender_delete_discoverylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Doświadczenie (XP)'),
        ),
    ]
