# Generated by Django 6.0.4 on 2026-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_profile_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='play_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Suma odtworzeń albumu'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(db_index=True, verbose_name='Data wydania'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='xp',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Doświadczenie (XP)'),
        ),
        migrations.AlterField(
            model_name='song',
            name='play_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Liczba odtworzeń'),
        ),
        migrations.AlterField(
            model_name='songplay',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data odtworzenia'),
        ),
    ]
