# Generated by Django 6.0.4 on 2026-04-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_alter_album_play_count_alter_album_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Data polubienia')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_album_positions', to='music.album')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_album_positions', to='music.profile')),
            ],
            options={
                'verbose_name': 'Polubiony album',
                'verbose_name_plural': 'Polubione albumy',
                'ordering': ['order', '-added_at'],
                'unique_together': {('profile', 'album')},
            },
        ),
    ]
