# Generated by Django 6.0.4 on 2026-04-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0037_likedalbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_albums',
        ),
    ]
