# Generated by Django 6.0.4 on 2026-04-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_remove_profile_liked_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_albums',
            field=models.ManyToManyField(blank=True, through='music.LikedAlbum', to='music.album'),
        ),
    ]
