# Generated by Django 6.0.4 on 2026-05-01 13:15

import imagekit.models.fields
import music.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0039_profile_liked_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='albums/', verbose_name='Okładka'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='artists/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='genres/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, validators=[music.validators.validate_no_profanity], verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=200, validators=[music.validators.validate_no_profanity], verbose_name='Nazwa playlisty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Napisz coś o sobie i swoim guście muzycznym', max_length=500, validators=[music.validators.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[music.validators.validate_no_profanity], verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration_sec',
            field=models.PositiveIntegerField(default=0, help_text='Czas trwania (automatycznie z pliku)', verbose_name='Czas trwania (s)'),
        ),
    ]
