# Generated by Django 6.0.4 on 2026-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_alter_album_cover_alter_artist_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration_sec',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Czas trwania (automatycznie z pliku)', verbose_name='Czas trwania (s)'),
        ),
    ]
