# Generated by Django 6.0.4 on 2026-05-01 13:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0041_alter_song_duration_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nickname', unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
