# Generated by Django 6.0.4 on 2026-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0042_alter_album_slug_alter_artist_slug_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_discovery',
            field=models.BooleanField(default=False, verbose_name='Playlista odkryć'),
        ),
    ]
