# Generated by Django 6.0.4 on 2026-05-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0043_playlist_is_discovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa playlisty'),
        ),
    ]
